apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-management
spec:
  selector:
    matchLabels:
      app: inventory-management
  replicas: 2
  strategy:
    type: inventory-management
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: inventory-management
    spec:
      containers:
        - name: inventory-management
          image: ashini98/inventory-management-application:{{tag}}
          ports:
            - containerPort: 8080
