apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: inventory-management
  name: inventory-management
spec:
  ports:
    - protocol: TCP
      port: 8080
  selector:
    app: inventory-management
  type: LoadBalancer
